<?xml version="1.0"?>
<package format="2">

  <name>uware</name>
  <version>0.0.1</version>
  <description>uware</description>
  <author email="pl.negre@uib.cat">Pep Lluis Negre</author>
  <maintainer email="pl.negre@uib.cat">Pep Lluis Negre</maintainer>
  <license>BSD</license>
  <url type="website">https://github.com/srv/uware</url>
  <url type="bugtracker">https://github.com/srv/uware/issues</url>
  <!-- Dependencies can be catkin packages or system dependencies -->
  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>tf</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>cola2_msgs</build_depend>
  <build_depend>ned_tools</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>image_transport</build_depend>
  <build_depend>message_filters</build_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>image_geometry</build_depend>
  <!--build_depend>libhaloc</build_depend-->
  <build_depend>pcl_ros</build_depend>
  <build_depend>cmake_modules</build_depend>
  <build_depend>tf_conversions</build_depend>
  <!-- <build_depend>orb_utils</build_depend> -->

  <exec_depend>roscpp</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cola2_msgs</exec_depend>
  <exec_depend>ned_tools</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>message_filters</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_geometry</exec_depend>
  <!--exec_depend>libhaloc</exec_depend-->
  <exec_depend>pcl_ros</exec_depend>
  <exec_depend>tf_conversions</exec_depend>
  <!-- <exec_depend>orb_utils</exec_depend> -->

<!-- The export tag contains other, unspecified, tags -->
  <export>
  </export>

</package>
